name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install fastapi uvicorn[standard]
        pip install -r apiTestPython/requirements.txt
    - name: Clear cache
      run: |
        echo "Clearing cache..."
        rm -rf __pycache__ .pytest_cache/
    - name: Build project
      run: |
        echo "Building project..."
        # Adicione aqui os comandos de construção, se necessário
    - name: Run tests
      run: |
        echo "Running tests..."
        pytest apiTestPython/tests


